name: Readme Update

on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "30 14 * * *"  # UTC 14:30 (KST 23:30)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5    
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser
      
      - name: Update README
        run: |
          python readme_update.py
      
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code README.md || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Commit README
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git config --local user.email "dskang207@gmail.com"
          git config --local user.name "ehdtjr"
          git add README.md
          git commit -m "Update README.md with latest blog posts"
          git push origin main